TWITTER_URL = "https://x.com/elfutboldenorte"
YOUTUBE_URL = "https://www.youtube.com/channel/UCpSVu6zV_CzeX2aFaUf-_7g"
WEB_URL = "https://balanzofit.com/"
INSTAGRAM_URL = "https://www.instagram.com/elfutboldelnorte/"
REPO_URL = "https://github.com/Alex-coder-software/El-Partido-del-A-o-WEB"